# Generated by Django 4.2.23 on 2025-08-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sold_price',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='', upload_to='player_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder')], default='Batsman', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='base_price',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
