# Generated by Django 4.2.23 on 2025-08-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_player_is_sold_remove_player_sold_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
