# Generated by Django 4.2.23 on 2025-08-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_player_current_price_player_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='sold_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
