# Generated by Django 4.2.23 on 2025-08-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_player_is_sold_player_sold_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sold_price',
        ),
        migrations.AddField(
            model_name='player',
            name='is_unsold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_price',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
