# Generated by Django 4.2.23 on 2025-08-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_remove_player_sold_remove_player_sold_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_unsold',
        ),
    ]
