# Generated by Django 4.2.23 on 2025-08-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_player_current_price_remove_player_is_unsold'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='initial_base_price',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
