# Generated by Django 4.2.23 on 2025-08-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_player_initial_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='player',
            name='initial_base_price',
        ),
        migrations.AddField(
            model_name='player',
            name='bid_price',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder')], max_length=50),
        ),
    ]
