# Generated by Django 4.2.23 on 2025-08-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_remove_player_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_been_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_unsold',
            field=models.BooleanField(default=False),
        ),
    ]
